//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChurchMember
    {
        public int ID { get; set; }
        public int ChurchId { get; set; }
        public int PriestId { get; set; }
        public string PositionHeld { get; set; }
        public string Status { get; set; }
        public string Department { get; set; }
    }
}
