//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentPlus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContentPlusEntities : DbContext
    {
        public ContentPlusEntities()
            : base("name=ContentPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NewsAdmin> NewsAdmins { get; set; }
        public DbSet<Article> Articles { get; set; }
        public DbSet<Priest> Priests { get; set; }
        public DbSet<Church> Churches { get; set; }
        public DbSet<ChurchMember> ChurchMembers { get; set; }
        public DbSet<Curia> Curias { get; set; }
        public DbSet<CuriaMember> CuriaMembers { get; set; }
        public DbSet<DailyMessage> DailyMessages { get; set; }
        public DbSet<Eparchy> Eparchies { get; set; }
        public DbSet<InstitutionMember> InstitutionMembers { get; set; }
        public DbSet<Institution> Institutions { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Parish> Parishes { get; set; }
    }
}
