//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuriaMember
    {
        public int Id { get; set; }
        public int CuriaId { get; set; }
        public int PriestId { get; set; }
        public string Department { get; set; }
        public string Positionheld { get; set; }
        public string Status { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
    }
}
