//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentPlus.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class DailyMessage
    {
        public int ID { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Message { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
    }
}
