//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsAdmin
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public string FilePath { get; set; }
        public int CategoryID { get; set; }
        public int DisplaySectionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public Nullable<bool> IsMarkDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
