//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parish
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Estd { get; set; }
        public string Patron { get; set; }
        public string Diocese { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Fbid { get; set; }
        public string Vicar { get; set; }
        public string Asstvicar1 { get; set; }
        public string Asstvicar2 { get; set; }
        public string District { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
    }
}
