//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentPlus.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class Priest
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Diocese { get; set; }
        public string Parish { get; set; }
        [AllowHtml]
        public string LongDesc { get; set; }
        public string HomeDiocese { get; set; }
        public string HomeParish { get; set; }
        public string Seminary { get; set; }
        public string DOB { get; set; }
        public string DateOfOrdination { get; set; }
        public string MaritalStatus { get; set; }
        public string Education { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentAddress { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pin { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Photo { get; set; }
        public string OtherDetails1 { get; set; }
        public string OtherDetails2 { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
    }
}
